### ISSUE TITLE
Editing settings

### ISSUE THREAD

**Issue by Hinkiii** [Galactic-Dev/iSponsorBlock#10]
On the desktop chrome version I have it configured to skip intros I can understand others might not like that but there’s also things like end cards that can be skipped in the native version

**Comment by Galactic-Dev** [comment]
> On the desktop chrome version I have it configured to skip intros I can understand others might not like that but there’s also things like end cards that can be skipped in the native version 

Yeah, the current version of iSponsorBlock is using the legacy API which doesn't support things like that, but in the new version which is getting pretty close to release already supports this.

**Comment by Galactic-Dev** [comment]
This was added in the new update
