### ISSUE TITLE
Options to hide buttons in title bar during playback 

### ISSUE THREAD

**Issue by rml9ty** [Galactic-Dev/iSponsorBlock#11]
![F5C09DA3-24AB-4E84-8C5F-80D6E63C03AD](https://user-images.githubusercontent.com/51538059/105572529-f510f800-5d57-11eb-8b04-948508cf9375.jpeg)

I would an option to hide those button while a video is playing. 😇

Loving the tweak btw (was using the earlier version which just... worked 👌)

**Comment by Galactic-Dev** [comment]
This option should already be in settings under the "Show iSponsorBlock Buttons in Video Player" switch. Let me know if this is what you wanted

**Comment by rml9ty** [comment]
this is exactly what I wanted. thanks so much for adding it!
