### ISSUE TITLE
Behaves as if it’s disabled when it’s enabled

### ISSUE THREAD

**Issue by Excremation** [Galactic-Dev/iSponsorBlock#115]
**Describe the bug**
iSponsorBlock is behaving as if it’s disabled when it is enabled. It does not detect or skip sponsor segments in any videos.

**To Reproduce**
I am using the latest version said to have fixed the app crashing on viewing videos, compiled into the uYou Enhanced app.

**Expected behavior**
Sponsor segments should be identified and skipped over.

**Please complete the following information:**
 - iOS Version: 15.4.1
 - Device: iPhone 13 Pro
 - YouTube Version: 19.12.3
 - iSponsorBlock Version: Unsure, latest?

**Additional context**
Sorry I couldn’t find anywhere on the github describing what version of iSponsorBlock is the current one.

**Comment by PoomSmart** [comment]
Not reproducable. Does it still happen?

**Comment by Excremation** [comment]
> Not reproducable. Does it still happen?

Just checked and it seems to be working now. The green segments of the seeker bar were up in the middle of the video but this was probably just a one time visual glitch. No idea what the issue was :S

**Comment by PoomSmart** [comment]
The bug with the segments being above the video progress bar should already be fixed in the very latest commit of iSB.
