### ISSUE TITLE
Crashed Report - 1.2.6 - Rootless

### ISSUE THREAD

**Issue by AnCry1596** [Galactic-Dev/iSponsorBlock#118]
**Describe the bug**
Crashed when update from 1.2.5 to 1.2.6 on rootless

**To Reproduce**
1. Update iSponsorBlock to 1.2.6
2. Play any not YouTube Short Videos
3. The YouTube app will freeze few seconds and crash

**Expected behavior**
When I play a video, YouTube app will freeze for few seconds and crash, and a new crash log show in KrashKop, I uploaded it at the last of this report.

**Screenshots**

**Please complete the following information:**
 - iOS Version: 15.6 RC
 - Device: iPhone 8 Plus
 - YouTube Version: 19.21.3
 - iSponsorBlock Version: 1.2.6

**Additional context**
This is list of other tweak I used with my YouTube app: uYou 3.0.1, uYouCrashFix 1.0, Return YouTube Dislike 1.11.11.
It works normally with 1.2.5 but crash on 1.2.6
My crash log file - From KrashKop
[text.txt](https://github.com/user-attachments/files/15540869/text.txt)

**Comment by ErvanJaeger** [comment]
Also crashed on taurine 14.3

**Comment by iqbal1992** [comment]
I also just build uyouplus with youtube 19.22.3 and uYou 3.0.4 and my youtube app also crashes and only solution is to turn off the iSponsorBlock

**Comment by AnCry1596** [comment]
I updated my YouTube to 19.22.3, iSponsorBlock 1.2.5 make my YouTube app crashes, but 1.2.6 make it works like normal. That is so weird

**Comment by iCrazeiOS** [comment]
Fixed in 1.2.7
