### ISSUE TITLE
visual bug I noticed on the latest versions of the tweak

### ISSUE THREAD

**Issue by 3m4r5** [Galactic-Dev/iSponsorBlock#12]
some times [this](https://user-images.githubusercontent.com/63432932/105638836-a6f61480-5e7d-11eb-981e-fa2979fcc31e.mov) happens

**Comment by Galactic-Dev** [comment]
ok. i'll work on a fix for it in the next update

**Comment by Galactic-Dev** [comment]
fixed in latest update
