### ISSUE TITLE
Latest version (1.2.7) completely bricks the YouTube app

### ISSUE THREAD

**Issue by Weather-OS** [Galactic-Dev/iSponsorBlock#123]
**Describe the bug**
Upgrading from version 1.2.6 to 1.2.7 results in the YouTube app segfaulting on launch

**To Reproduce**
1. Update YouTube (19.35.3)
2. Update iSponsorBlock
3. Launch YouTube

**Expected behavior**
launch

**Please complete the following information:**
 - iOS Version: 16.0
 - Device: iPhone: 13
 - YouTube Version: 19.35.3
 - iSponsorBlock Version: 1.2.7

**Additional context**
Reverting to 1.2.6 fixes this issue.

**Comment by PoomSmart** [comment]
Crash log?

**Comment by Weather-OS** [comment]
I should probably first test out the latest git commit.
