### ISSUE TITLE
another visual bug I noticed on the latest versions of the tweak

### ISSUE THREAD

**Issue by 3m4r5** [Galactic-Dev/iSponsorBlock#13]
sometimes also [this](https://user-images.githubusercontent.com/63432932/105640275-d872de00-5e85-11eb-8d9e-c8de3b2ec0e8.mov) happens

**Comment by Galactic-Dev** [comment]
not sure what the visual bug is here, could you explain it?

**Comment by 3m4r5** [comment]
(look at the video player timeline) the red color froze / lagged behind

**Comment by Galactic-Dev** [comment]
> (look at the video player timeline) the red color froze / lagged behind

ah ok i see that now. what youtube version are you on?

**Comment by 3m4r5** [comment]
15.49.4 (latest)

**Comment by Galactic-Dev** [comment]
Closing because its been over a year and this issue seems to have disappeared in new YouTube versions.
