### ISSUE TITLE
[Feature Request] An option to show only one button in video player

### ISSUE THREAD

**Issue by 3m4r5** [Galactic-Dev/iSponsorBlock#15]
I only want this button
![C24B1C09-4DAE-4F72-AAEF-3EB1C0634AE3](https://user-images.githubusercontent.com/63432932/106173708-e9309600-619c-11eb-9c48-e74bfb8520c8.jpeg)

**Comment by Galactic-Dev** [comment]
ok

**Comment by PoomSmart** [comment]
#79
