### ISSUE TITLE
New versions causing crashes

### ISSUE THREAD

**Issue by RexyAU** [Galactic-Dev/iSponsorBlock#16]
Hello,

I have been injecting iSponsorBlock.deb into Cercube (using iPAPatcher by Brandon Plank) for use on non-jailbroken devices by sideloading via AltStore. 

However, version 0.0.3 is the last that currently works because >v1.0 is causing an instant app crash after the YouTube splash screen.

I'm guessing that the crashes are because these new isponsorblock versions have configurable options and its not playing nicely inside the sandboxed app. Would you be able make a custom version that doesn't have any configurable options (like v0.0.3 and earlier) if this is what is causing the crashing?

Thanks.

Btw, here is the reddit post:
https://www.reddit.com/r/sideloaded/comments/kn1yfp/release_cercubeprovp9_for_1440p_and_4k_youtube/

https://appdb.to/app/cydia/1900000752

**Comment by Galactic-Dev** [comment]
yeah this version needs some tweaking to be sideloadable. i was going to make a sideloadable version myself, so i'm going to close this issue.
