### ISSUE TITLE
sideloadable ipa

### ISSUE THREAD

**Issue by bingoxo** [Galactic-Dev/iSponsorBlock#17]
hi , saw your comment in reddit saying you're working on a sideloadable ipa , i created this issue to keep track of it , not rushing or anything , and thanks again for this awesome tweak

**Comment by Galactic-Dev** [comment]
ok thanks i'll update progress here

**Comment by draumaz** [comment]
Love to know if this is still in the works

**Comment by Galactic-Dev** [comment]
> Love to know if this is still in the works

i can't get any of the ipa patching tools to work properly

**Comment by bingoxo** [comment]
> > Love to know if this is still in the works
> 
> i can't get any of the ipa patching tools to work properly

i found versions of youtube patched with your tweak but i think it's using an older version , is that what you want to do ? i can't link it because it's definetly breaking some Tos somewhere lol .

is your plan to make a youtube ipa with your tweak or an ipa of your tweak to be installed alongside youtube ?

**Comment by Galactic-Dev** [comment]
the only way to do it jailed it to patch the ipa with my tweak. and yeah the versions i've seen are using version 0.0.3 at the latest which is super old. if anyone wants to take up patching this into an ipa they can, but they'll probably have to change some stuff since i keep some assets in a part of the filesystem jailed ios can't access.

**Comment by bingoxo** [comment]
> the only way to do it jailed it to patch the ipa with my tweak. and yeah the versions i've seen are using version 0.0.3 at the latest which is super old. if anyone wants to take up patching this into an ipa they can, but they'll probably have to change some stuff since i keep some assets in a part of the filesystem jailed ios can't access.

yeah i cant see the settings for your tweak in those patched ipas so it must be an old version , maybe you can use this to help : https://github.com/Al4ise/Azule
https://www.reddit.com/r/sideloaded/comments/m8h3jt/release_cercube_ipa_for_nonjailbreak_users/

**Comment by Luewii** [comment]
I have a sideloadable compiled deb (v1.0-6, according to the control file) working on YT v16.10.5. I was able to patch along side Cercube, Aldris, and YTUHD without any issues. See my fork of the project. I will include changes to the code ASAP.

**Comment by Galactic-Dev** [comment]
> I have a sideloadable compiled deb (v1.0-6, according to the control file) working on YT v16.10.5. I was able to patch along side Cercube, Aldris, and YTUHD without any issues. See my fork of the project. I will include changes to the code ASAP.

Nice, I'll close this issue then and point to that fork for anyone asking.

**Comment by draumaz** [comment]
I attempted to patch the YouTube IPA with the deb provided above, and I'm finding it crashing on boot.

**Comment by Galactic-Dev** [comment]
> I attempted to patch the YouTube IPA in Azule with the deb provided above, and I'm finding it crashing on boot. Perhaps I'm not aware of the correct way to go about this?

Not sure. Try getting a crash log from Settings->Privacy->Analytics->Analytics Data, and send it here

**Comment by draumaz** [comment]
Looks like it's a problem with libcolorpicker.
![](https://user-images.githubusercontent.com/77967471/113072512-0b826800-917c-11eb-9bc7-0e6a923499b7.jpg)

**Comment by Luewii** [comment]
> Looks like it's a problem with libcolorpicker.
> ![](https://user-images.githubusercontent.com/77967471/113072512-0b826800-917c-11eb-9bc7-0e6a923499b7.jpg)

Try patching with Alderis (ws.hbang.alderis). You can get the deb from https://www.ios-repo-updates.com/repository/chariz/package/ws.hbang.alderis/

**Comment by draumaz** [comment]
>
> Try patching it alongside Alderis (ws.hbang.alderis). You can get the deb from https://www.ios-repo-updates.com/repository/chariz/package/ws.hbang.alderis/

Can confirm that this works!

**Comment by bingoxo** [comment]
> > Try patching it alongside Alderis (ws.hbang.alderis). You can get the deb from https://www.ios-repo-updates.com/repository/chariz/package/ws.hbang.alderis/
> 
> Can confirm that this works!

can you please give me step by step how to do it ? and where did you get the .deb from ?

**Comment by draumaz** [comment]
> 
> can you please give me step by step how to do it ? and where did you get the .deb from ?

I used the newest Cercube IPA I could find. I patched it with Azule  using the Alderis deb and the SponsorBlock deb from Luewii provided earlier. I then sideloaded the resulting IPA via AltStore.

**Comment by iMonZ** [comment]
The big problem why iSponsorBlock doesn't work is because it tries to find/install files to system directories.
Could you try to add a pre compiler if clause: if the tweak is going to be build to an IPA app then it installs the assets and libraries to the IPA directory and make calls to it instead of system directories?
This should theoretically work, and I found the png files and the Cercube.dylib that aren't in the system directories which makes sense in a non-jailbroken phone.
This patch wouldn't work if you build this for the Actual tweak because in jailbroken mode you just can't add files to the actual app

**Comment by iMonZ** [comment]
> The big problem why iSponsorBlock doesn't work is because it tries to find/install files to system directories.
> Could you try to add a pre compiler if clause: if the tweak is going to be build to an IPA app then it installs the assets and libraries to the IPA directory and make calls to it instead of system directories?
> This should theoretically work, and I found the png files and the Cercube.dylib that aren't in the system directories which makes sense in a non-jailbroken phone.
> This patch wouldn't work if you build this for the Actual tweak because in jailbroken mode you just can't add files to the actual app

On AppDB there is a working version of iSponsorBlock IPA file, but he has completely removed all buttons etc to avoid pain.
This could be a proof that the method of my last message could work.

**Comment by bingoxo** [comment]
> > can you please give me step by step how to do it ? and where did you get the .deb from ?
> 
> I used the newest Cercube IPA I could find. I patched it with Azule using the Alderis deb and the SponsorBlock deb from Luewii provided earlier. I then sideloaded the resulting IPA via AltStore.

you're not jailbroken right ? , i don't know what i did wrong but i still cant get it to work (latest youtube ipa though 16.11.3) , do you mind sharing the ipa with me please ? (you got ytuhd as well ? )

**Comment by draumaz** [comment]
> > > can you please give me step by step how to do it ? and where did you get the .deb from ?
> > 
> > 
> > I used the newest Cercube IPA I could find. I patched it with Azule using the Alderis deb and the SponsorBlock deb from Luewii provided earlier. I then sideloaded the resulting IPA via AltStore.
> 
> you're not jailbroken right ? , i don't know what i did wrong but i still cant get it to work (latest youtube ipa though 16.11.3) , do you mind sharing the ipa with me please ? (you got ytuhd as well ? )

Nope, I'm not jailbroken. I don't know if I'm allowed to share IPAs on Github, so I'll just say the exact file name that I used is 'cercube_v5.2.12.ipa'. I should note that I did not use any other tweaks in Azule, only the base Cercube IPA and the iSponsorBlock deb provided by @Luewii.

**Comment by iMonZ** [comment]
> > > > can you please give me step by step how to do it ? and where did you get the .deb from ?
> > > 
> > > 
> > > I used the newest Cercube IPA I could find. I patched it with Azule using the Alderis deb and the SponsorBlock deb from Luewii provided earlier. I then sideloaded the resulting IPA via AltStore.
> > 
> > 
> > you're not jailbroken right ? , i don't know what i did wrong but i still cant get it to work (latest youtube ipa though 16.11.3) , do you mind sharing the ipa with me please ? (you got ytuhd as well ? )
> 
> Nope, I'm not jailbroken. I don't know if I'm allowed to share IPAs on Github, so I'll just say the exact file name that I used is 'cercube_v5.2.12.ipa'. I should note that I did not use any other tweaks in Azule, only the base Cercube IPA and the iSponsorBlock deb provided by @Luewii.

Can you link the tools that you have used?
Or tweaks

**Comment by draumaz** [comment]
> Can you link the tools that you have used?
> Or tweaks

[Azule](https://github.com/Al4ise/Azule)

[Cercube IPA](https://iosninja.io/ipa-library/download-cercube-4-ipa-ios)

[Alderis deb](https://www.ios-repo-updates.com/repository/chariz/package/ws.hbang.alderis/)

[iSponsorBlock deb](https://github.com/Luewii/iSponsorBlock)

**Comment by iMonZ** [comment]
Thanks!
I try that later

**Comment by Galactic-Dev** [comment]
> > The big problem why iSponsorBlock doesn't work is because it tries to find/install files to system directories.
> 
> > Could you try to add a pre compiler if clause: if the tweak is going to be build to an IPA app then it installs the assets and libraries to the IPA directory and make calls to it instead of system directories?
> 
> > This should theoretically work, and I found the png files and the Cercube.dylib that aren't in the system directories which makes sense in a non-jailbroken phone.
> 
> > This patch wouldn't work if you build this for the Actual tweak because in jailbroken mode you just can't add files to the actual app
> 
> 
> 
> On AppDB there is a working version of iSponsorBlock IPA file, but he has completely removed all buttons etc to avoid pain.
> 
> This could be a proof that the method of my last message could work.

This isn't a stripped down version of the tweak it's just a super old version lacking significant amounts of features.

**Comment by qnblackcat** [comment]
Hi everyone!
I finally got Cercube (5.2.12) & Youtube (16.11.3) & iSponsorblock working, at least for me 😅. I had to edit iSponsorblock (from @Luewii) a little bit. Feel free to try it. Also, please lets me know if it doesn't work

[iPA (Mediafire)](https://www.mediafire.com/file/aoubk22kjqgjbhw/CercubeNoAds_iSponsorBlock.ipa/file)

**Comment by spider623** [comment]
> Hi everyone!
> I finally got Cercube (5.2.12) & Youtube (16.11.3) & iSponsorblock working, at least for me 😅. I had to edit iSponsorblock (from @Luewii) a little bit. Feel free to try it. Also, please lets me know if it doesn't work
> 
> [iPA (Mediafire)](https://www.mediafire.com/file/aoubk22kjqgjbhw/CercubeNoAds_iSponsorBlock.ipa/file)

OK, I did using Appdb.to to sign,  it actually works

**Comment by bingoxo** [comment]
> Hi everyone!
> I finally got Cercube (5.2.12) & Youtube (16.11.3) & iSponsorblock working, at least for me 😅. I had to edit iSponsorblock (from @Luewii) a little bit. Feel free to try it. Also, please lets me know if it doesn't work
> 
> [iPA (Mediafire)](https://www.mediafire.com/file/aoubk22kjqgjbhw/CercubeNoAds_iSponsorBlock.ipa/file)

Can you add ytuhd please ?

**Comment by qnblackcat** [comment]
> > Hi everyone!
> > I finally got Cercube (5.2.12) & Youtube (16.11.3) & iSponsorblock working, at least for me 😅. I had to edit iSponsorblock (from @Luewii) a little bit. Feel free to try it. Also, please lets me know if it doesn't work
> > [iPA (Mediafire)](https://www.mediafire.com/file/aoubk22kjqgjbhw/CercubeNoAds_iSponsorBlock.ipa/file)
> 
> Can you add ytuhd please ?

If iSponsorblock does work, I'll add YTUHD as well. YTUHD is not a problem with Azule 😅

**Comment by spider623** [comment]
i tested 2 LTT videos, it works xD

**Comment by qnblackcat** [comment]
> > Hi everyone!
> > I finally got Cercube (5.2.12) & Youtube (16.11.3) & iSponsorblock working, at least for me 😅. I had to edit iSponsorblock (from @Luewii) a little bit. Feel free to try it. Also, please lets me know if it doesn't work
> > [iPA (Mediafire)](https://www.mediafire.com/file/aoubk22kjqgjbhw/CercubeNoAds_iSponsorBlock.ipa/file)
> 
> OK, I did using Appdb.to to sign, it actually works

Are 

> i tested 2 LTT videos, it works xD

Hi! Are you jailbroken? I just want to make sure it works on non-jb devices.

**Comment by qnblackcat** [comment]
> i tested 2 LTT videos, it works xD

Hi! Are you jailbroken? I just want to make sure it works on non-jb devices.

**Comment by spider623** [comment]
> > i tested 2 LTT videos, it works xD
> 
> Hi! Are you jailbroken? I just want to make sure it works on non-jb devices.

no jailbreak stock, only appdb.to pro, it should work with altstore.io too

**Comment by bingoxo** [comment]
> > i tested 2 LTT videos, it works xD
> 
> Hi! Are you jailbroken? I just want to make sure it works on non-jb devices.

non jailbroken and works fine with altstore , now ytuhd please :D

**Comment by iMonZ** [comment]
Can someone show me a sample of how you are using the Azule command? The help can't help me

**Comment by qnblackcat** [comment]
> > > i tested 2 LTT videos, it works xD
> > 
> > 
> > Hi! Are you jailbroken? I just want to make sure it works on non-jb devices.
> 
> non jailbroken and works fine with altstore , now ytuhd please :D

https://www.mediafire.com/folder/j3wegkcry698i/_Cercube
Please save the IPA on your device. I will remove it in the future

**Comment by spider623** [comment]
> > > > i tested 2 LTT videos, it works xD
> > > 
> > > 
> > > Hi! Are you jailbroken? I just want to make sure it works on non-jb devices.
> > 
> > 
> > non jailbroken and works fine with altstore , now ytuhd please :D
> 
> https://www.mediafire.com/folder/j3wegkcry698i/_Cercube
> Please save the IPA on your device. I will remove it in the future

done, thanks for the ipa

**Comment by bingoxo** [comment]
thanks everyone for making this work , i'm curious though if the latest 1.0.7 of the tweak (and future ones) can be made to work in jailed mode

**Comment by qnblackcat** [comment]
> thanks everyone for making this work , i'm curious though if the latest 1.0.7 of the tweak (and future ones) can be made to work in jailed mode

@Luewii 

> I have a sideloadable compiled deb (v1.0-6, according to the control file) working on YT v16.10.5. I was able to patch along side Cercube, Aldris, and YTUHD without any issues. See my fork of the project. I will include changes to the code ASAP.

Hi! Will you update your fork of iSponsorBlock to v1.0-7?

**Comment by qnblackcat** [comment]
> I have a sideloadable compiled deb (v1.0-6, according to the control file) working on YT v16.10.5. I was able to patch along side Cercube, Aldris, and YTUHD without any issues. See my fork of the project. I will include changes to the code ASAP.

Will you update your fork of iSponsorBlock to 1.0-7?

**Comment by Luewii** [comment]
I've updated my fork to 1.0-8 :)

**Comment by iMonZ** [comment]
> Can someone show me a sample of how you are using the Azule command? The help can't help me

So should you select the deb? Or only the ".dylib" files, and how can I select resources in Azule?
The manual doesn't help me

**Comment by qnblackcat** [comment]
> > Can someone show me a sample of how you are using the Azule command? The help can't help me
> 
> So should you select the deb? Or only the ".dylib" files, and how can I select resources in Azule?
> The manual doesn't help me

You can select the deb OR the dylib. 

Resources file? Azule auto-detect it and add any .bundle to the ipa

**Comment by iMonZ** [comment]
> > > Can someone show me a sample of how you are using the Azule command? The help can't help me
> > 
> > 
> > So should you select the deb? Or only the ".dylib" files, and how can I select resources in Azule?
> > The manual doesn't help me
> 
> You can select the deb OR the dylib.
> 
> Resources file? Azule auto-detect it and add any .bundle to the ipa

Oh, that's amazing so with -f I should select my compiled debs?

And what if there is a framework like you have in Cercube? Should -f work there too? But the frameworks shouldn't be injected right?

Sorry I'm new here and there are still a few things that I don't understand.
But still thank you for your help!

**Comment by qnblackcat** [comment]
> > > > Can someone show me a sample of how you are using the Azule command? The help can't help me
> > > 
> > > 
> > > So should you select the deb? Or only the ".dylib" files, and how can I select resources in Azule?
> > > The manual doesn't help me
> > 
> > 
> > You can select the deb OR the dylib.
> > Resources file? Azule auto-detect it and add any .bundle to the ipa
> 
> Oh, that's amazing so with -f I should select my compiled debs?
> 
> And what if there is a framework like you have in Cercube? Should -f work there too? But the frameworks shouldn't be injected right?
> 
> Sorry I'm new here and there are still a few things that I don't understand.
> But still thank you for your help!

Wait. How did you use Azule. Just type in "Azule" in any terminal window, then follow the instructions

**Comment by iMonZ** [comment]
> > > > > Can someone show me a sample of how you are using the Azule command? The help can't help me
> > > > 
> > > > 
> > > > So should you select the deb? Or only the ".dylib" files, and how can I select resources in Azule?
> > > > The manual doesn't help me
> > > 
> > > 
> > > You can select the deb OR the dylib.
> > > Resources file? Azule auto-detect it and add any .bundle to the ipa
> > 
> > 
> > Oh, that's amazing so with -f I should select my compiled debs?
> > And what if there is a framework like you have in Cercube? Should -f work there too? But the frameworks shouldn't be injected right?
> > Sorry I'm new here and there are still a few things that I don't understand.
> > But still thank you for your help!
> 
> Wait. How did you use Azule. Just type in "Azule" in any terminal window, then follow the instructions

I did this command: 
`
azule -n Cercube -i ~/AzuleWorking/test/cercube\(16.10.5\ T5.2.12\).ipa -o ~/AzuleWorking/test/output/ -f ~/AzuleWorking/test/ws.hbang.alderis_1.1.2_iphoneos-arm.deb, ~/AzuleWorking/test/com.galacticdev.isponsorblock_1.0-8-2+debug_iphoneos-arm.deb, ~/AzuleWorking/test/com.ps.ytuhd_0.0.3.7_iphoneos-arm.deb -d libcolorpicker.dylib, com.galacticdev.isponsorblock.bundle, iSponsorBlock.dylib, YTUHD.dylib`

I get this error in the Console:
```
/usr/local/bin/azule:222: no matches found: Payload/*.app/Frameworks/libcolorpicker.dylib,
/usr/local/bin/azule:223: no matches found: Payload/*.app/Frameworks/libcolorpicker.dylib,
/usr/local/bin/azule:222: no matches found: Payload/*.app/Frameworks/com.galacticdev.isponsorblock.bundle,
/usr/local/bin/azule:223: no matches found: Payload/*.app/Frameworks/com.galacticdev.isponsorblock.bundle,
/usr/local/bin/azule:222: no matches found: Payload/*.app/Frameworks/iSponsorBlock.dylib,
/usr/local/bin/azule:223: no matches found: Payload/*.app/Frameworks/iSponsorBlock.dylib,
```
And the app is crashing!

And with the command Azule I don't know how to separate everything.
