### ISSUE TITLE
a new bug?

### ISSUE THREAD

**Issue by 3m4r5** [Galactic-Dev/iSponsorBlock#24]
[this](https://user-images.githubusercontent.com/63432932/115674969-d9b58900-a356-11eb-84c9-50f7fcf843cf.mov) (the appearing of the splash that contains the text "RTX 3080 Ti spotted" ) is a new behavior, wasn't happening in previous iSponsorBlock versions.

 - iOS Version: 14.3
 - Device: iPhone 8 Plus
 - YouTube Version 16.14.2
 - iSponsorBlock Version 1.0-9

**Comment by Galactic-Dev** [comment]
Not sure if it's a bug. It might be a new YouTube a/b testing feature where it shows the name of the "chapter" you're seeking to when you double tap. I'm assuming this is a techlinked video, and you can see the chapter names in the description of the video.

**Comment by 3m4r5** [comment]
yes it is a TechLinked video but the double tap thing was never getting triggered with iSponsorBlock in previous versions

**Comment by Galactic-Dev** [comment]
Closing because new YouTube updates seem to have made this no longer happen
