### ISSUE TITLE
Squished sponsorblock icon

### ISSUE THREAD

**Issue by Fadexz** [Galactic-Dev/iSponsorBlock#25]
The icon in the navigation bar will be squeezed horizontally on launch of the app.

1. Open YouTube app

The icon should fit normally without it being small horizontally.

![image](https://user-images.githubusercontent.com/37004055/116991808-77766400-ad18-11eb-8dff-2a809535ddb6.jpeg)

 - iOS Version: 14.3
 - Device: iPhone X
 - YouTube Version: 16.16.4
 - iSponsorBlock Version: 1.0-9

Entering the app again or tapping the icon can fix the layout.

**Comment by Galactic-Dev** [comment]
Thanks for the report. I've gotten it before and I'm still trying to recreate the issue

**Comment by Galactic-Dev** [comment]
It's been a year and I haven't had anymore reports of this bug, so I'm closing this issue for now.
