### ISSUE TITLE
Tweak doesn’t inject on iPad

### ISSUE THREAD

**Issue by Deniz1433** [Galactic-Dev/iSponsorBlock#27]
**Describe the bug**
This tweak works perfectly on my phone but doesn't inject at all on my iPad. Both on Youtube version 16.20.5 (Latest)

**To Reproduce**
Launch Youtube on iPad
See that it's vanilla and untweaked

**Please complete the following information:**
 - iOS Version: 12.4.8
 - Device: iPad mini 2
 - YouTube Version 16.20.5
 - iSponsorBlock Version 1.0-10

**Additional context**
The iSponsorblock button and options aren't there, doesn't skip or show sponsored segments. (Maybe because the tweak doesn't inject at all to the iPad version of Youtube, which might be slightly different than the phone version.)

**Comment by Galactic-Dev** [comment]
this is an issue with ios 12, and i'm working on an ios 12 version but there are some bugs i have to work on before i release it

**Comment by leodoi3** [comment]
I'm on iOS 12.4.8 on iPad Air and I also have this same exact problem.

**Comment by ilyamodder** [comment]
Same problem. iPad Air, iOS 12.5.4.

**Comment by salotor** [comment]
I have an iPad Air with iOS 12.4.
Tweak (version 0.1) worked with YouTube 15.30.3, recently stopped working. I updated the tweak to version 1.0-10, it does not work too, like the commentators above.
