### ISSUE TITLE
NOT AN ISSUE | Just a THANK YOU 👍🏻

### ISSUE THREAD

**Issue by MikeeI** [Galactic-Dev/iSponsorBlock#28]
I m using SponsorBlock on my Desktop for years and a few weaks ago i saw the iOS version. And i was like OMG 😮🤤❤️

Thank you for making this tweak! It makes YouTube such a pleasure.

Developers don’t get much credit, so THANK YOU VERY MUCH from Austria.

![1FB46850-6C0D-4D4D-8CF4-EF930E107326](https://user-images.githubusercontent.com/13944905/120710852-f51bc400-c4be-11eb-97ce-465625878d6f.jpeg)

**Comment by Galactic-Dev** [comment]
Thanks, I'm glad you like the tweak
