### ISSUE TITLE
Bugs...

### ISSUE THREAD

**Issue by xAstroBoy** [Galactic-Dev/iSponsorBlock#3]
It Doesn't skip the very start of the video if it contains a sponsored fragment. 
also it doesn't multiple fragments according to code is just able to skip 2 fragments...
why you dont colorize the fragments position on the youtube app?

**Comment by Galactic-Dev** [comment]
All of these are being addressed in an upcoming update.

**Comment by xAstroBoy** [comment]
Thanks, can't wait for it.

**Comment by Galactic-Dev** [comment]
New updated just released. All of these problems were addressed so i'm closing this issue 😄
