### ISSUE TITLE
Add the Preview/Recap category

### ISSUE THREAD

**Issue by exurd** [Galactic-Dev/iSponsorBlock#31]
**Is your feature request related to a problem? Please describe.**
This new feature was added to the official extension/repository [26 days ago](https://github.com/ajayyy/SponsorBlock/issues/444#issuecomment-864646127).

**Describe the solution you'd like**
To keep compatibility, the new category must be added to this repository.

**Additional context**
This is the category's description from [the wiki](https://github.com/ajayyy/SponsorBlock/wiki/Segment-Categories):
> **Preview/Recap** Quick recap of previous episodes, or a preview of what's coming up later in the current video. Meant for edited together clips, not for spoken summaries.

**Comment by exurd** [comment]
Please include this in the next release.

**Comment by Galactic-Dev** [comment]
Moved to issue #49
