### ISSUE TITLE
The assumption of data type is wrong

### ISSUE THREAD

**Issue by PoomSmart** [Galactic-Dev/iSponsorBlock#32]
**Describe the bug**

https://github.com/Galactic-Dev/iSponsorBlock/blob/166d539593a27f433c4d9923b2dff1015651ab45/iSponsorBlock.xm#L198

The return type is `NSMutableArray` and you don't need to perform additional mutable operations. You can directly modify the array and so that YouPiP doesn't need to resort to this workaround because of an unexpected data type change at runtime: https://github.com/PoomSmart/YouPiP/blob/78d5a331a172ad9d5500ab865ac1563bc3134530/Tweak.x#L126

**Comment by Galactic-Dev** [comment]
Thanks for letting me know, I'll change this.

**Comment by PoomSmart** [comment]
@Galactic-Dev Any updates?

**Comment by Galactic-Dev** [comment]
Fixed in latest commit, so the next version I release will have the correct code.
