### ISSUE TITLE
Add the Highlight category

### ISSUE THREAD

**Issue by exurd** [Galactic-Dev/iSponsorBlock#33]
**Is your feature request related to a problem? Please describe.**
A new category was added into [Sponsorblock 3.0](https://github.com/ajayyy/SponsorBlock/releases/tag/3.0) that allows for the user to  [skip to the highlight of the video](https://blog.ajay.app/highlight-sponsorblock).

**Describe the solution you'd like**
Add this category (as well as #31) to stay consistent with the official repo/extension.

**Describe alternatives you've considered**
There are no other alternatives (other than ignoring the issue(s) 🤨)

**Additional context**
Description of the category from [the wiki](https://wiki.sponsor.ajay.app/index.php/Segment_Categories):
> **Highlight**
[This is for getting to the point or highlight of the video.](https://wiki.sponsor.ajay.app/index.php/Highlight)

**Comment by Galactic-Dev** [comment]
I'll add this to the todo list for the next update.

**Comment by Galactic-Dev** [comment]
Moved to issue #49. I am currently working on the new update which will include all the new categories!
