### ISSUE TITLE
Version of the tweak for Apple TV?

### ISSUE THREAD

**Issue by PencilNotPen** [Galactic-Dev/iSponsorBlock#36]
Would it be possible to create a version of this tweak for Apple TV, jailed and jailbroken? Such that users could use something like IPAPatcher to combine it with the Apple TV Youtube.ipa for use on a jailed or jailbroken Apple TV?

Thanks!

**Comment by Galactic-Dev** [comment]
I looked into making an Apple TV version a few months ago, but the youtube app is completely different on there, and I had no idea how to even begin making an iSponsorBlock version for it. The app on there is very odd, and is very hard to tweak. So, I don't think it's going to be possible, at least for me.

**Comment by dmunozv04** [comment]
I know it’s not the same thing, but I recently started development of [iSponsorBLockTV](https://github.com/dmunozv04/iSponsorBlockTV), a client for AppleTV that relies in a computer to do the skipping, this way it can be done on a jailed device
