### ISSUE TITLE
JB and NON-JB support

### ISSUE THREAD

**Issue by dayanch96** [Galactic-Dev/iSponsorBlock#37]
Hi. Slightly changed the paths to the icons, created a bundle so that icons are displayed correctly on devices with and without JB. if you find it useful, please visit my fork (as i'm new in github i don't know how else to suggest it)

https://github.com/dayanch96/iSponsorBlock

**Comment by dayanch96** [comment]
Created pull request.

**Comment by binnichtaktiv** [comment]
> Created pull request.

Could you plz update to the latest version 🙃

**Comment by dayanch96** [comment]
> Could you plz update to the latest version 🙃

Done, Thanks for letting know. :)
