### ISSUE TITLE
Segments appear high above the progress bar

### ISSUE THREAD

**Issue by Terrain2** [Galactic-Dev/iSponsorBlock#39]
**Describe the bug**
The segments show up above the progress bar instead of in front of it.

**Steps to reproduce**
1. Open video with SponsorBlock segments
2. Go to home page and have it play in miniplayer
3. Open video again

**Screenshots**
[here is a tweet that contains a screenshot of the issue](https://twitter.com/terrain222/status/1489731720312246279)

**Please complete the following information:**
 - iOS 14.3
 - Device: iPhone SE 2020
 - YouTube Version 17.04.3
 - iSponsorBlock Version 1.0-12

**Additional context**
~~I have absolutely no idea what caused this~~ but i did find it amusing so i thought i'd report it anyways. ~~This seems to be a one-off bug of some sort and i don't think it consistently happens~~. Fullscreening and going back to the splitscreen video/comments view fixes it. ~~It might also have occurred when reentering the app after having the video paused in the background since it happened again when i reentered after writing this, and i experimented about with doing so and could not reproduce it consistently.~~ Actually it seems to be caused by reentering the video from the in-app miniplayer, i managed to reproduce it consistently.

Here are the other youtube tweaks i have installed as well, since they may be related

- Return Youtube Dislike 1.6.2
- Cercube 5.3.4
- YouPiP 1.6.5
- YTABGoodes 1.0.1

**Comment by Galactic-Dev** [comment]
Should be fixed in the newest update, lmk if it doesn't work for you
