### ISSUE TITLE
Crashing on YT 15.31.3

### ISSUE THREAD

**Issue by TGC-TECH** [Galactic-Dev/iSponsorBlock#4]
I am on iOS 13.6 latest version of Cercube. YT 15.31.3. As soon as it tries to skip the app crashes. If you can't reproduce the issue and want logs let me know.

**Comment by Scunkaneli** [comment]
works on 15.34.3 for me

**Comment by Galactic-Dev** [comment]
It would be helpful if you could send logs, I am aware of a few bugs and am starting to work on them now.

**Comment by 2600box** [comment]
how do we get logs for isponsorblock?

**Comment by TGC-TECH** [comment]
I wonder if you can just copy the debug info for YT? I just reinstalled isponsor block to try to get the logs and the issue is gone now... so I guess reinstalling fixed whatever was happening before.

**Comment by Galactic-Dev** [comment]
> how do we get logs for isponsorblock?

install the cr4shed tweak from packix, and it should give you the crash log if/when youtube crashes

**Comment by Galactic-Dev** [comment]
All crashes should be fixed in the new update
