### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Vreex** [Galactic-Dev/iSponsorBlock#40]
**Describe the bug**
Not working in tested and up-to-date YouTube versions.

**To Reproduce**
Step 1: Open YouTube.

**Expected behavior**
Same as YouTube Vanced.

**Screenshots**
A stock and unmodified YouTube should do.

**Please complete the following information:**
 - iOS Version: 12.5.2
 - Device: iPhone 6
 - YouTube Version: 15.31.3 - 17.05.2
 - iSponsorBlock Version: 1.0-13

**Additional context**
Might add it as comment.

**Comment by Galactic-Dev** [comment]
try installing iSponsorBlockLegacy from my repo, it should work on iOS 12 devices
