### ISSUE TITLE
Can’t find a source to download

### ISSUE THREAD

**Issue by leodoi3** [Galactic-Dev/iSponsorBlock#41]
**Describe the bug**

**To Reproduce**
1. Download from cydia 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46114199/154393744-d84dc6f2-f6a5-49c6-b6de-732f232b2e6f.png)

**Please complete the following information:**
 - iOS Version: 1 2.4.8 
 - Device: iPad Air
 - YouTube Version 16.46.5
 - iSponsorBlock Version 1.0-13

**Additional context**

**Comment by Galactic-Dev** [comment]
try using a more modern package manager such as zebra
