### ISSUE TITLE
Short length of segment gets infinite loop

### ISSUE THREAD

**Issue by MPThLee** [Galactic-Dev/iSponsorBlock#48]
**Describe the bug**
If segment has very short length by total length (segment_length/total_video_length), Video get infinite loop.

**To Reproduce**
1. Go to https://youtu.be/JYaGTmSroMc
2. Click on 1:33
3. See error

**Expected behavior**
Skipped.

**Screenshots**
https://sendvid.com/xlzmauzd

**Please complete the following information:**
 - iOS Version: 15.4
 - Device: iPad mini
 - YouTube Version: 17.05.2
 - iSponsorBlock Version: 6173112585c9afa5cc32107014ba339faff99d3e

**Additional context**
Here's sb db that i've got this bug: https://sb.ltn.fi/video/JYaGTmSroMc/

**Comment by PoomSmart** [comment]
Can't reproduce it anymore.

**Comment by MPThLee** [comment]
I’ve got there’s another video that this issue happens: https://youtu.be/qQk94CjRvIs
https://sendvid.com/s4dkvr8a
![IMG_0196](https://github.com/Galactic-Dev/iSponsorBlock/assets/26970092/c0fc2f6a-c93b-4cc2-a1b5-77dc691bca88)

**Comment by JulianAvilaP** [comment]
@MPThLee Can you reproduce it with https://www.youtube.com/watch?v=9B0yX0UIN9M? There's a segment at the start that is 0.207 seconds long and causes an infinite loop for me. Mind you this is with uYouEnhanced so it could be using a very outdated version of iSponsorBlock.
