### ISSUE TITLE
Sponsor Segment crashes YouTube 17.30.1

### ISSUE THREAD

**Issue by derduesentrieb** [Galactic-Dev/iSponsorBlock#52]
Under 17.29.3 the issue is not present.

**Comment by Plasmapea987** [comment]
-[YTPlayerViewController scrubToTime:]: unrecognized selector sent to instance 0x122104c00

Crashing whit isponsorblock (intro)

**Comment by iCrazeiOS** [comment]
fixed in 0b6bd1a3ba5698885f2c16a02fa86e5a54855c5c

**Comment by Galactic-Dev** [comment]
fixed thanks to icraze's pr. new update w/ the fix is now live on my repo
