### ISSUE TITLE
Crash when trying to play video

### ISSUE THREAD

**Issue by shadowscott** [Galactic-Dev/iSponsorBlock#55]
**Describe the bug**
Trying to play a video and YouTube app crashes Immediately

**Please complete the following information:**
 - iOS Version: iPadOS 14.7.1
 - Device: iPad Air 2
 - YouTube Version 17.30.3
 - iSponsorBlock Version [e.g. 1.0-7] latest

**Additional context**
[<YTMainAppControlsOverlayView 0x11f019190> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _isOverlayVisible.

**Comment by Galactic-Dev** [comment]
Can you send a full crash log please

**Comment by shadowscott** [comment]
[text.txt](https://github.com/Galactic-Dev/iSponsorBlock/files/9300670/text.txt)
