### ISSUE TITLE
Changing device orientation brokes YT

### ISSUE THREAD

**Issue by dayanch96** [Galactic-Dev/iSponsorBlock#56]
**Describe the bug**
Segments display brokes YT overlay.

**To Reproduce**
1. Open any video with sponsored segments
2. Change orientation to Landscape and back to Portrait
3. See error

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - iOS Version: 15.6.1
 - Device: iPhone 11
 - YouTube 17.37.3]
 - iSponsorBlock Version [latest]

**Additional context**
AFAIK segments for overlay needs fix.

**Comment by arichorn** [comment]
We all have this issue, I recommend using 17.36.4 until it’s solved by the dev alright 👍

**Comment by dayanch96** [comment]
> We all have this issue, I recommend using 17.36.4 until it’s solved by the dev alright 👍

Well, thanks. It’s known workaround. I’m left this issue here because dev bit busy and may not be aware about this bug.
