### ISSUE TITLE
Add Audio Notification On Skip

### ISSUE THREAD

**Issue by yodaluca23** [Galactic-Dev/iSponsorBlock#58]
Add the Audio Notification On Skip like the SponsorBlock extension has. Also please make it the same tone so that people who use both the extension and this will hear it both the same.

Images:

![image](https://user-images.githubusercontent.com/67206487/196085299-0b4cf6e1-78be-4817-bb13-5474f25e8077.png)
![image](https://user-images.githubusercontent.com/67206487/196085368-a367a24b-3bee-4632-a323-a6aa450a9290.png)

**Comment by PoomSmart** [comment]
#79
