### ISSUE TITLE
[Bug] Skip ads only first time

### ISSUE THREAD

**Issue by lucidyan** [Galactic-Dev/iSponsorBlock#6]
#### System:
IOS: 13.5
Cercube: 5.2.7
Youtube: 15.42.2

#### Reproduce steps:
- Open video before ad (timecode A)
- iSponsorBlock skips ad
- Back to timecode A
- iSponsorBlock plays the ad

Behavior persists before reopening video

**Comment by Galactic-Dev** [comment]
I'm aware of this issue and I'm currently working on a fix

**Comment by Galactic-Dev** [comment]
Fixed
