### ISSUE TITLE
Add support for custom APIs

### ISSUE THREAD

**Issue by thesuperzapper** [Galactic-Dev/iSponsorBlock#61]
I think we can fairly easily add a config so users can specify which sponsor block API they want to use.

Obviously, the default would still be 'https://sponsor.ajay.app/', but with a config, people could use mirrors when that is down.

The only thing we might need to be careful about is not submitting new segments to mirrors, or at least warning users if they try.

**Comment by PencilNotPen** [comment]
Yes, the server is often down. A post here provides an aggregated replacement server, which can be used:

https://r.nf/r/SponsorBlock/comments/ykel11/aggregated_alternate_servers/

Even if providing a non-standard server is not ideal, adding a field to change the server at the user's discretion would be very valuable. The browser extension already supports this.

Thanks

**Comment by iCrazeiOS** [comment]
added in eaf58e4dd7f9846ea87688dd74974a008e1b6263 / a94dcc58cbbeaf5fee45de83677eb9e5c6b02b00
