### ISSUE TITLE
Freezes app on >17.36.4

### ISSUE THREAD

**Issue by derduesentrieb** [Galactic-Dev/iSponsorBlock#63]
When trying to exit full screen mode by tapping the minimize button, the app freezes and needs to be force closed. 

**To Reproduce**
- be above yt version 17.36.4
- play video
- enter full screen
- tap minimize button

**Please complete the following information:**
 - iOS Version: 14.3
 - Device: iPhone 11 Pro
 - YouTube Version >17.36.4
 - iSponsorBlock Version: newest

**Comment by faz-cxr** [comment]
I have the same bug. The app freezes and is forced to close - 
When swiping up (to go full screen) or
clicking the full screen icon!

**Comment by Delamcode** [comment]
Same. iPadOS 15 (sideloaded with trollstore) iPad Air 5

**Comment by MarioLuigi0404** [comment]
I’ve been having this issue get for ages and today it got to the point where simply swiping down to try putting the video in the miniplayer just instantly crashes the app

**Comment by Delamcode** [comment]
Try this fork: https://github.com/qnblackcat/iSponsorBlock/tree/eb19fd1089f4a940cf1e3df48c6f064ea9a65cf6

**Comment by PoomSmart** [comment]
Fixed in the newest version.
