### ISSUE TITLE
Stuck on splash screen on iOS 15

### ISSUE THREAD

**Issue by DetachHead** [Galactic-Dev/iSponsorBlock#65]
**Describe the bug**
The YouTube app gets stuck on the splash screen when isponsorblock is installed

**To Reproduce**
1. Install from Sileo
2. Open YouTube app

**Expected behavior**
App loads

**Screenshots**

![image](https://user-images.githubusercontent.com/57028336/206302080-36c48023-11e2-44f8-991b-a22baa181130.png)

**Please complete the following information:**
 - iOS Version: 15.1.1
 - Device: iPhone 13
 - YouTube Version 17.43.1
 - iSponsorBlock Version 1.0-15

**Additional context**
It works in uYouPlus, but not when I install the tweaks directly from Sileo (which I believe is the recommended method when jailbroken)

**Comment by PoomSmart** [comment]
Fixed in #69
