### ISSUE TITLE
Installation repo is dead?

### ISSUE THREAD

**Issue by SevastianGit** [Galactic-Dev/iSponsorBlock#68]
**Describe the bug**
The repository to get this tweak, https://galacticdev.me/ is down.

**To Reproduce**
1. Go to 'https://galacticdev.me/'
2. Site doesn't even load, no store can load this.

**Expected behavior**
I add https://galacticdev.me/ as a repository/source to Sileo/Cydia whatever, it loads and lets me install the iSponsorblock tweak.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/76776905/216006868-9871e10b-9ce9-4264-8d92-8f6838c091ab.png)

**Please complete the following information:**
 - iOS Version: 12.5.6
 - Device: iPhone 5s
 - YouTube Version Latest that supports the 5s
 - iSponsorBlock Version Latest?

**Additional context**
If you can't provide us with a proper repo or download link, please at least explain us how we could build/create the tweak itself to install ourselves from the source code you shared.

**Comment by asdfzxcvbn** [comment]
not too hard to build, mostly the same as other theos-based tweaks.

`git clone https://github.com/Galactic-Dev/iSponsorBlock && cd iSponsorBlock`

`wget https://github.com/Muirey03/RemoteLog/raw/master/RemoteLog.h -O $THEOS/include/RemoteLog.h`

`make package FINALPACKAGE=1`

and now your deb is in `./packages`.

**Comment by PoomSmart** [comment]
https://repo.icrazeios.com new repo for iSB
