### ISSUE TITLE
[FeatureRequest] Mark ad fragments with markers

### ISSUE THREAD

**Issue by lucidyan** [Galactic-Dev/iSponsorBlock#7]
Example from Chrome extension:
![image](https://user-images.githubusercontent.com/5789108/97197955-4e9c7180-17bf-11eb-8b29-cb406a043c69.png)

**Comment by Galactic-Dev** [comment]
This is actively being worked on for the next release of iSponsorBlock, and I've already made a lot of progress with it.

**Comment by Galactic-Dev** [comment]
Added
