### ISSUE TITLE
Unskipping the second sponsor in a video will seek to the beginning of the first sponsor

### ISSUE THREAD

**Issue by iCrazeiOS** [Galactic-Dev/iSponsorBlock#78]
**To Reproduce**
1. Go to https://www.youtube.com/watch?v=LuVpwB1s8iU
2. Skip the second segment (does not matter if you skip the first one beforehand)
3. Unskip
4. You will be taken to the start of the first segment

**Expected behavior**
Be taken to the start of the unskipped (second) segment

I do not knowhow this behaves on videos with 3+ segments. I don't know of any.

Latest iSB, latest YT.

**Comment by dayanch96** [comment]
Not sure yet, but guess that it happens only in AVQueuePlayer

**Comment by iCrazeiOS** [comment]
Fixed
