### ISSUE TITLE
Can’t get past splashscreen

### ISSUE THREAD

**Issue by burakdede0** [Galactic-Dev/iSponsorBlock#82]
**Describe the bug**
YouTube hangs on splashscreen with iSponsorBlock 1.2.

**To Reproduce**
1. Update iSponsorBlock to 1.2. 
2. Open YouTube

**Expected behavior**
App should open and pass the splashscreen after a few seconds.

**Please complete the following information:**
 - iOS Version: 15.7.5
 - Device: iPhone 7
 - YouTube Version 18.22.9
 - iSponsorBlock Version 1.2

**Additional context**

Using palera1n Rootless. Downgrading iSponsorBlock to 1.1.1 fixes the issue.

**Comment by dayanch96** [comment]
I have installed iSB 1.2 and no issues. same yt and device.

**Comment by burakdede2001** [comment]
I was able to fix the issue by disabling aaaSnowBoardUISB extension for YouTube with Choicy.
