### ISSUE TITLE
DeArrow Support

### ISSUE THREAD

**Issue by j5155** [Galactic-Dev/iSponsorBlock#84]
**Describe the solution you'd like**
Support for https://github.com/ajayyy/DeArrow, made by the same person as SponsorBlock but it replaces titles and thumbnails with crowdsourced ones. I think it would be very cool to use this extension on iOS as well.

**Describe alternatives you've considered**
Starting a new project instead of adding it to this one.

**Comment by dayanch96** [comment]
it has nothing to do with isponsorblock. rather tweak request
