### ISSUE TITLE
Doesn't work on latest versions of Youtube and Substrate Safe Mode :(

### ISSUE THREAD

**Issue by storm2513** [Galactic-Dev/iSponsorBlock#9]
Really nice tweak, one of my favs.

iPadOS 13.5.1, checkra1n. Last working Youtube version is 15.39.4. Also it stopped working with Substrate Safe Mode 0.9.6005 (new version, previous works fine).

Can you provide some guide on how to develop it locally and contribute?
Also it would be great if you could add some comments over the code, so even people that are new to jailbreak and Objective-C could understand what's going on.

**Comment by Galactic-Dev** [comment]
I'm working on a new update that is pretty close to release. I will add more comments in the next release. If you want to learn how to make jb tweaks try looking on r/jailbreakdevelopers and join https://discord.gg/7BFYUgUS

**Comment by Galactic-Dev** [comment]
New update released
